# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AppleWS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.2'
  pod 'AlamofireImage', '~> 3.2'
  pod 'AlamofireNetworkActivityIndicator', '~> 2.1’
  pod 'AlamofireObjectMapper', '~> 4.0'
  pod 'AsyncDisplayKit'
  pod 'RealmSwift', '~> 2.1'
  pod 'Instabug'
  pod 'SimplePDF'
  pod 'PromiseKit/Photos'
end
